name: Build Bunject Solution
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - autobuild

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1.2.0

      - name: Download Paquerette Binaries
        env:
          STEAM_APP_ID: ${{ vars.STEAM_APP_ID }}
        run: |
          echo "SteamApp ID: $env:STEAM_APP_ID"
          $PaqPath = (Join-Path -Path $PWD.Path -ChildPath \paquerette\)
          echo "Target install: $PaqPath"
          steamcmd +force_install_dir $PaqPath +login "${{ secrets.STEAM_ACCOUNT }}" "${{secrets.STEAM_PASSWORD}}" +app_update $env:STEAM_APP_ID +quit

      - name: Download BepInEx Binaries
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'bepinex/bepinex'
          out-file-path: '.\bepinex\'
          extract: true
          fileName: 'BepInEx_win_x64_*.zip'
          tag: 'v5.4.23.4'

      - name: Build Bunject Solution
        run: |
          $BepInExPath = ("bepinex" | Resolve-Path).Path
          echo "BepInEx: $BepInExPath"
          Get-ChildItem -Path $BepInExPath -Recurse -Directory -Force 

          $PaqPath = ("paquerette" | Resolve-Path).Path
          echo "PaqPath: $PaqPath"

          Get-ChildItem -Path $BepInExPath -Recurse -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName

          msbuild Bunject.sln /p:Configuration=Release /p:PaquerettePath="$PaqPath" /p:BepInExPath="$BepInExPath"

      - name: Build BNYS Zip
        run: |
          mkdir Release
          Copy-Item -Path ".\\Bunject\\bin\\Release\\Bunject.dll" -Destination ".\\Release\\"
          Copy-Item -Path ".\\BunjectComputer\\bin\\Release\\Bunject.Computer.dll" -Destination ".\\Release\\"
          Copy-Item -Path ".\\BunjectNewYardSystem\\bin\\Release\\Bunject.NewYardSystem.dll" -Destination ".\\Release\\"
          Copy-Item -Path ".\\BunjectNewYardSystem\\Assets\\BNYS\\" -Destination ".\\Release\\BNYS\\" -Recursive

          Compress-Archive -Path ".\\Release\\" -DestinationPath "BNYSRelease.zip"

      - name: Create BNYS Release
        shell: bash
        run: |
          gh release create latest -p ./BNYSRelease.zip -t Test Release


